server:
  port: 8004

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: gaoyipeng
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

