server:
  port: 8080

spring:
  redis:
    database: 0
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
    sentinel:
      master: mymaster
      nodes: 192.168.67.130:26379,192.168.67.130:26380,192.168.67.130:26381
    password: 123456
